### PR TITLE
Fix cleaning up abort listener

### LINKED ISSUE #75: Memory leak when using abort signals
We have encountered a memory leak issue. After an extensive search for the source of the leak, it was found that it occurred in pMap. Upon reviewing the source code of your package, I discovered that you subscribe to the AbortSignal event but do not unsubscribe from it, which causes the memory leak.

### PR DESCRIPTION
**Pull request by liuhanqu**
Fixes #75

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -30,20 +30,34 @@ export default async function pMap(
...
 		const iterator = iterable[Symbol.iterator] === undefined ? iterable[Symbol.asyncIterator]() : iterable[Symbol.iterator]();
 
+		const signalListener = () => {
+			reject(signal.reason);
+		};
+
+		const cleanup = () => {
+			if (signal) {
+				signal.removeEventListener('abort', signalListener);
+			}
```
Comment (sindresorhus) [inline index.js:40]:
```suggestion
			signal?.removeEventListener('abort', signalListener);
```
